name: Sabatex.RadzenBlazor.Demo
env:
  PUBLISH_DIR: Sabatex.RadzenBlazor.Demo/bin/Release/net8.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]
    paths:
      - 'Sabatex.RadzenBlazor.Demo/Sabatex.RadzenBlazor.Demo.csproj'
permissions: 
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: ls
      run : ls -l -R
       
    # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    #- name: Change base-tag in index.html from / to Sabatex.RadzenBlazor
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/Sabatex.RadzenBlazor\/" \/>/g' Sabatex.RadzenBlazor.Demo/wwwroot/index.html

    - name: Publish app
      run: dotnet publish  Sabatex.RadzenBlazor.Demo/Sabatex.RadzenBlazor.Demo.csproj  -c Release -o:publish -p:GHPages=true
      

    # Deploy the site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: publish/wwwroot
        force_orphan: true
